version: "3"

services:
    db:
        image: mysql
        container_name: ta_si_medical_center_clinic_ks_db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "33062:3306"
        volumes:
            - ta_si_medical_center_clinic_ks_data:/var/lib/mysql

volumes:
    ta_si_medical_center_clinic_ks_data:
